import type { GridItem } from "../4-organisms/cards/card.types";

// Last updated date for display in the Terms of Service page
export const termsLastUpdated = "February 1, 2026";

export const termsSections: GridItem[] = [
	// Section 1 — Scope and acceptance of the agreement
	{
		title: "1. Acceptance of Terms",
		content:
			'By accessing, browsing, or using the SkillVector platform ("Service"), including any associated APIs, documentation, software development kits, and related services, you ("User", "you", or "your") acknowledge that you have read, understood, and agree to be bound by these Terms of Service ("Terms", "Agreement"), together with our Privacy Policy and Cookie Policy, which are incorporated herein by reference. If you are accepting these Terms on behalf of a company, organization, or other legal entity, you represent and warrant that you have the authority to bind such entity to these Terms, in which case "you" and "your" shall refer to such entity. If you do not agree to any provision of these Terms, you must immediately discontinue use of the Service.',
		centered: false,
	},

	// Section 2 — Definitions used throughout the agreement
	{
		title: "2. Definitions",
		content:
			"For the purposes of this Agreement, the following terms shall have the meanings set forth below:",
		items: [
			'"Service" refers to the SkillVector platform, including the web application, REST API, vector search engine, embedding pipeline, and all related tools, documentation, and infrastructure.',
			'"Content" means any data, text, professional profiles, skills data, search queries, configuration files, or other materials uploaded to, generated by, or transmitted through the Service.',
			'"User Data" refers to any information, files, or materials that you submit, upload, or otherwise provide to the Service, including but not limited to professional profile data in CSV, JSON, or plain text format.',
			'"Embedding" means the numerical vector representation of textual data generated by AI models integrated with or used by the Service.',
			'"Third-Party Provider" refers to any external service integrated with SkillVector, including but not limited to OpenAI, Anthropic, Google AI, HuggingFace, Cohere, and Ollama.',
		],
		centered: false,
	},

	// Section 3 — Open-source license grant
	{
		title: "3. License Grant and Open-Source Terms",
		content:
			"SkillVector is open-source software distributed under the MIT License. Subject to the terms and conditions of this Agreement and the MIT License, you are hereby granted a non-exclusive, worldwide, royalty-free license to:",
		subsections: [
			{
				title: "3.1 Permitted Uses",
				content:
					"Use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software. You may incorporate SkillVector into proprietary or commercial products, modify the source code to suit your requirements, create derivative works, and deploy self-hosted instances without restriction on the number of users or volume of data processed.",
			},
			{
				title: "3.2 License Conditions",
				content:
					"The above copyright notice and the MIT License permission notice shall be included in all copies or substantial portions of the Software. Attribution to the original SkillVector project is required in derivative works. The license does not grant you rights to use the SkillVector name, logo, or trademarks for promotional purposes without prior written consent.",
			},
			{
				title: "3.3 Hosted Service Terms",
				content:
					"If you access SkillVector through our hosted service (rather than a self-hosted deployment), additional terms may apply. The hosted service is provided on an as-available basis, and we reserve the right to impose usage limits, rate limiting, storage quotas, or other restrictions as necessary to ensure fair access and system stability for all users.",
			},
		],
		centered: false,
	},

	// Section 4 — User account and registration obligations
	{
		title: "4. Account Registration and Security",
		content:
			"Certain features of the Service may require you to create an account or provide API credentials. When you register for an account or configure API access, you agree to the following obligations:",
		items: [
			"Provide accurate, current, and complete information during the registration process and keep your account information up to date at all times.",
			"Maintain the confidentiality and security of your API keys, passwords, tokens, and any other credentials used to access the Service. You are solely responsible for all activity that occurs under your account.",
			"Notify us immediately using the project's GitHub issue tracker if you become aware of any unauthorized access to or use of your account, or any other breach of security; please label the issue 'security' so it can be triaged promptly.",
			"You may not share, transfer, or assign your account credentials to any third party without our prior written consent. Any unauthorized use of credentials may result in immediate suspension or termination of your access.",
			"We reserve the right to suspend or terminate accounts that remain inactive for more than twelve (12) consecutive months, or accounts that are reasonably suspected of violating these Terms.",
		],
		centered: false,
	},

	// Section 5 — Prohibited conduct and acceptable use
	{
		title: "5. Acceptable Use and Prohibited Conduct",
		content:
			"You agree to use the Service only for lawful purposes and in accordance with these Terms. Without limiting the generality of the foregoing, you expressly agree not to:",
		subsections: [
			{
				title: "5.1 System Integrity",
				content:
					"Upload, transmit, or distribute any malicious code, viruses, worms, Trojan horses, ransomware, spyware, or any other harmful or disruptive software or data. You shall not interfere with, disrupt, or attempt to gain unauthorized access to the Service, its servers, networks, or any connected systems. You shall not probe, scan, or test the vulnerability of the Service or any related system or network without express written authorization.",
			},
			{
				title: "5.2 Data and Content",
				content:
					"Upload personal data without proper consent and a valid legal basis under applicable privacy and data protection laws, including but not limited to the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), and any other relevant legislation. You shall not upload, store, or transmit any content that is defamatory, obscene, threatening, abusive, or that infringes upon intellectual property rights of any third party. You shall not use the Service to facilitate identity theft, phishing, social engineering, or any form of fraud.",
			},
			{
				title: "5.3 Service Abuse",
				content:
					"Engage in any automated scraping, crawling, or data harvesting that exceeds reasonable API usage or circumvents rate limits. You shall not use the Service to build a competing product or service, or to reverse-engineer proprietary algorithms or embedding models. You shall not attempt to bypass, disable, or circumvent any security feature, access control, or usage limitation of the Service. You shall not resell, lease, or sublicense access to the hosted Service without authorization.",
			},
		],
		centered: false,
	},

	// Section 6 — User data responsibilities
	{
		title: "6. User Data and Data Processing",
		content:
			"You retain all rights, title, and interest in and to your User Data. By uploading User Data to the Service, you grant SkillVector a limited, non-exclusive, royalty-free license to process, store, index, and generate vector embeddings of your User Data solely for the purpose of providing the Service to you.",
		subsections: [
			{
				title: "6.1 Data Controller Responsibilities",
				content:
					"Where you upload personal data of third parties (e.g., professional profiles of employees, candidates, or contractors), you are the data controller and bear sole responsibility for ensuring compliance with all applicable data protection laws. This includes, but is not limited to, obtaining informed consent from data subjects, providing appropriate privacy notices, maintaining records of processing activities, conducting data protection impact assessments where required, and honoring data subject access requests.",
			},
			{
				title: "6.2 Data Processing Agreement",
				content:
					"For organizations processing personal data through the hosted SkillVector service, a Data Processing Agreement (DPA) is available upon request. The DPA outlines our obligations as a data processor, including sub-processor disclosures, data breach notification procedures, data transfer mechanisms, and technical and organizational security measures.",
			},
			{
				title: "6.3 Data Retention and Deletion",
				content:
					"You may delete your User Data at any time through the Service interface or API. Upon account termination, we will delete or anonymize your User Data within thirty (30) days, unless retention is required by law or to resolve pending disputes. Vector embeddings derived from deleted data will be purged from the Qdrant database during the same period. Backup copies may persist in encrypted archival storage for up to ninety (90) days before permanent deletion.",
			},
		],
		centered: false,
	},

	// Section 7 — Intellectual property rights
	{
		title: "7. Intellectual Property",
		content:
			"Except for User Data and open-source components licensed under the MIT License, SkillVector and its licensors retain all rights, title, and interest in the Service, including all associated intellectual property rights. The SkillVector name, logo, and all related names, logos, product and service names, designs, and slogans are trademarks of SkillVector or its affiliates. You may not use such marks without prior written permission. Nothing in these Terms transfers to you any intellectual property owned by SkillVector or third parties, and all rights, title, and interest in such property shall remain solely with SkillVector or the respective rights holder.",
		centered: false,
	},

	// Section 8 — Third-party service integrations
	{
		title: "8. Third-Party Services and Integrations",
		content:
			"The Service integrates with various Third-Party Providers for AI embedding generation, model inference, and related functionality. Your use of any Third-Party Provider is governed by that provider's own terms of service, privacy policy, and acceptable use policy.",
		subsections: [
			{
				title: "8.1 Provider Responsibility",
				content:
					"We are not responsible for the availability, accuracy, reliability, or performance of any Third-Party Provider. We make no representations or warranties regarding the data handling practices, security measures, uptime guarantees, or compliance certifications of Third-Party Providers. Any data you transmit to a Third-Party Provider through the Service is subject to that provider's terms and policies.",
			},
			{
				title: "8.2 Self-Hosted Deployments",
				content:
					"If you deploy SkillVector using self-hosted AI models (e.g., Ollama), all data processing occurs on your own infrastructure. In such deployments, you are solely responsible for the security, availability, and legal compliance of your infrastructure, including any AI models you choose to run. SkillVector provides no warranty or support for third-party AI models used in self-hosted deployments.",
			},
		],
		centered: false,
	},

	// Section 9 — Warranty disclaimers
	{
		title: "9. Disclaimer of Warranties",
		content:
			'THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, SKILLVECTOR EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:',
		items: [
			"IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.",
			"ANY WARRANTY THAT THE SERVICE WILL MEET YOUR REQUIREMENTS, BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS, OR OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, OR SYSTEM.",
			"ANY WARRANTY AS TO THE ACCURACY, COMPLETENESS, RELIABILITY, OR QUALITY OF ANY SEARCH RESULTS, AI-GENERATED EMBEDDINGS, SKILL MATCHING, OR OTHER OUTPUT PRODUCED BY THE SERVICE.",
			"ANY WARRANTY REGARDING THE SECURITY OF YOUR DATA OR THAT DEFECTS WILL BE CORRECTED.",
			"ANY WARRANTY ARISING FROM COURSE OF DEALING, USAGE OF TRADE, OR COURSE OF PERFORMANCE.",
		],
		centered: false,
	},

	// Section 10 — Limitation of liability
	{
		title: "10. Limitation of Liability",
		content:
			"TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SKILLVECTOR, ITS AUTHORS, COPYRIGHT HOLDERS, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, CONTRIBUTORS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:",
		items: [
			"Loss of profits, revenue, goodwill, data, or business opportunities, whether direct or indirect.",
			"Cost of procurement of substitute goods, services, or technology.",
			"Business interruption, system downtime, or inability to access the Service.",
			"Inaccurate, incomplete, or misleading AI-generated search results, skill matches, or embeddings.",
			"Unauthorized access to or alteration of your data or transmissions.",
			"Any damages or losses arising from the use of Third-Party Provider services integrated with SkillVector.",
		],
		centered: false,
	},

	// Section 11 — Indemnification by user
	{
		title: "11. Indemnification",
		content:
			"You agree to indemnify, defend, and hold harmless SkillVector and its officers, directors, employees, agents, contributors, and licensors from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising from or relating to: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any rights of any third party, including intellectual property or privacy rights; (d) any User Data you upload to or process through the Service; or (e) your failure to comply with applicable data protection laws in connection with your use of the Service. This indemnification obligation shall survive the termination of your account and these Terms.",
		centered: false,
	},

	// Section 12 — Termination and suspension
	{
		title: "12. Termination and Suspension",
		content:
			"We may suspend or terminate your access to the Service at any time, with or without cause and with or without notice, for any reason including but not limited to a breach of these Terms.",
		subsections: [
			{
				title: "12.1 Effect of Termination",
				content:
					"Upon termination, your right to access and use the Service will immediately cease. We will make commercially reasonable efforts to allow you to export your User Data for a period of thirty (30) days following termination, unless termination was due to a violation of Section 5 (Acceptable Use). Provisions of these Terms that by their nature should survive termination shall survive, including but not limited to Sections 7 (Intellectual Property), 9 (Disclaimer of Warranties), 10 (Limitation of Liability), 11 (Indemnification), and 14 (Governing Law).",
			},
			{
				title: "12.2 Voluntary Termination",
				content:
					"You may terminate your account at any time by deleting your account through the Service interface or by opening an issue on the SkillVector GitHub repository for account termination support. Upon voluntary termination, we will delete your User Data in accordance with Section 6.3.",
			},
		],
		centered: false,
	},

	// Section 13 — Changes to the Terms
	{
		title: "13. Modifications to Terms",
		content:
			'We reserve the right to modify, amend, or replace these Terms at any time at our sole discretion. If we make material changes to these Terms, we will provide notice through the Service interface, by email, or by posting a revised version with a new "Last Updated" date. Material changes will become effective thirty (30) days after notice is provided. Non-material changes are effective immediately upon posting. Your continued use of the Service after the effective date of any modifications constitutes your acceptance of the revised Terms. If you do not agree to the modified Terms, you must discontinue use of the Service before the effective date.',
		centered: false,
	},

	// Section 14 — Governing law and dispute resolution
	{
		title: "14. Governing Law and Dispute Resolution",
		content:
			"These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.",
		subsections: [
			{
				title: "14.1 Dispute Resolution",
				content:
					"Any dispute, controversy, or claim arising out of or relating to these Terms or the Service shall first be submitted to good-faith informal negotiation for a period of at least thirty (30) days. If the dispute cannot be resolved through negotiation, it shall be submitted to binding arbitration administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules. The arbitration shall be conducted in the English language, and the arbitral award shall be final and binding upon both parties.",
			},
			{
				title: "14.2 Class Action Waiver",
				content:
					"TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION. If for any reason a claim proceeds in court rather than in arbitration, you and SkillVector each waive any right to a jury trial.",
			},
		],
		centered: false,
	},

	// Section 15 — General / boilerplate provisions
	{
		title: "15. General Provisions",
		items: [
			"Entire Agreement: These Terms, together with the Privacy Policy and Cookie Policy, constitute the entire agreement between you and SkillVector regarding the Service and supersede all prior agreements, representations, warranties, and understandings.",
			"Severability: If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, such provision shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect.",
			"Waiver: The failure of SkillVector to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. Any waiver must be in writing and signed by SkillVector.",
			"Assignment: You may not assign or transfer these Terms or your rights hereunder without our prior written consent. SkillVector may assign its rights and obligations under these Terms without restriction.",
			"Force Majeure: SkillVector shall not be liable for any failure or delay in performing obligations under these Terms caused by circumstances beyond its reasonable control, including but not limited to natural disasters, acts of government, pandemics, war, terrorism, labor disputes, power failures, internet disturbances, or failures of Third-Party Providers.",
			"Notices: Any notices required or permitted under these Terms will be provided via the project's GitHub repository (issues/discussions) or to the primary contact associated with your account.",
		],
		centered: false,
	},

	// Section 16 — Contact information
	{
		title: "16. Contact Information",
		content:
			"If you have any questions, concerns, or requests regarding these Terms of Service, please open an issue on the SkillVector GitHub repository or use the support channels listed in the project's README. For security-related issues, use GitHub's private security advisory or open an issue labeled 'security'. For data protection inquiries, open an issue labeled 'privacy' or follow the data subject request process described in the README. We will make commercially reasonable efforts to respond to all inquiries within five (5) business days.",
		centered: false,
	},
];
